const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PORT = 9000;
const OPENAPI_FILE = path.join(__dirname, '..', 'openapi.yaml');
const BUNDLED_FILE = path.join(__dirname, '..', 'bundled.yaml');
const ROOT_DIR = path.join(__dirname, '..');

let bundledYaml = '';
let lastModified = 0;
let isRebuilding = false;

// Function to rebuild the bundle
function rebuildBundle() {
  if (isRebuilding) {
    return; // Prevent concurrent rebuilds
  }
  
  isRebuilding = true;
  console.log('\n🔄 Rebuilding OpenAPI specification...');
  try {
    execSync('npm run bundle', { stdio: 'pipe', cwd: ROOT_DIR });
    if (fs.existsSync(BUNDLED_FILE)) {
      bundledYaml = fs.readFileSync(BUNDLED_FILE, 'utf8');
      lastModified = Date.now();
      console.log('✅ Bundle rebuilt successfully');
    }
  } catch (error) {
    console.error('❌ Error bundling OpenAPI spec:', error.message);
  } finally {
    // Delay resetting flag to prevent immediate retriggering
    setTimeout(() => {
      isRebuilding = false;
    }, 1000);
  }
}

// Initial bundle
if (!fs.existsSync(BUNDLED_FILE)) {
  console.log('Bundling OpenAPI specification...');
  rebuildBundle();
} else {
  bundledYaml = fs.readFileSync(BUNDLED_FILE, 'utf8');
  lastModified = fs.statSync(BUNDLED_FILE).mtimeMs;
}

// Watch for file changes (exclude openapi.yaml as it's generated by merge)
const watchPaths = [
  path.join(ROOT_DIR, 'paths'),
  path.join(ROOT_DIR, 'components'),
  path.join(ROOT_DIR, 'reference')
];

let rebuildTimeout;
function scheduleRebuild() {
  clearTimeout(rebuildTimeout);
  rebuildTimeout = setTimeout(rebuildBundle, 300); // Debounce rebuilds
}

watchPaths.forEach(watchPath => {
  if (fs.existsSync(watchPath)) {
    const stats = fs.statSync(watchPath);
    if (stats.isDirectory()) {
      // Watch directory recursively
      fs.watch(watchPath, { recursive: true }, (eventType, filename) => {
        // Ignore generated files and files changed during rebuild
        if (isRebuilding) return;
        
        if (filename && 
            !filename.includes('bundled.yaml') && 
            !filename.includes('openapi.yaml') && // openapi.yaml is generated by merge
            (filename.endsWith('.yaml') || filename.endsWith('.yml') || filename.endsWith('.md'))) {
          console.log(`\n📝 File changed: ${filename}`);
          scheduleRebuild();
        }
      });
    } else {
      // Don't watch openapi.yaml as it's generated by the merge process
      // Only watch source files in paths/ and components/
      if (!watchPath.endsWith('openapi.yaml')) {
        fs.watch(watchPath, (eventType, filename) => {
          if (isRebuilding) return;
          console.log(`\n📝 File changed: ${path.basename(watchPath)}`);
          scheduleRebuild();
        });
      }
    }
  }
});

// HTML template with Redoc (open-source) and hot reload
function getHtmlTemplate() {
  const currentTime = Date.now();
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WRPay API Documentation</title>
  <style>
    body {
      margin: 0;
      padding: 0;
    }
  </style>
</head>
<body>
  <div id="redoc-container"></div>
  <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
  <script>
    let redocInstance = null;
    let lastCheck = ${currentTime};
    
    function initRedoc() {
      const container = document.getElementById('redoc-container');
      container.innerHTML = '';
      redocInstance = Redoc.init('/bundled.yaml?t=' + Date.now(), {}, container);
    }
    
    initRedoc();
    
    // Hot reload: Poll for changes every 2 seconds
    setInterval(async () => {
      try {
        const response = await fetch('/bundled.yaml?t=' + Date.now());
        const headers = response.headers;
        const lastModifiedHeader = headers.get('last-modified');
        if (lastModifiedHeader) {
          const serverTime = new Date(lastModifiedHeader).getTime();
          if (serverTime > lastCheck) {
            console.log('🔄 Reloading documentation...');
            lastCheck = serverTime;
            initRedoc();
          }
        }
      } catch (error) {
        // Silently handle errors
      }
    }, 2000);
  </script>
</body>
</html>`;
}

const server = http.createServer((req, res) => {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  const url = req.url.split('?')[0]; // Remove query params
  const requestPath = url === '/' ? '/index.html' : url;

  if (requestPath === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(getHtmlTemplate());
  } else if (requestPath === '/bundled.yaml' || requestPath === '/openapi.yaml') {
    // Serve bundled.yaml for Redoc, or openapi.yaml for reference
    const fileToServe = requestPath === '/bundled.yaml' ? BUNDLED_FILE : OPENAPI_FILE;
    const stats = fs.existsSync(fileToServe) ? fs.statSync(fileToServe) : null;
    const lastModifiedTime = stats ? stats.mtime.toUTCString() : new Date().toUTCString();
    
    res.writeHead(200, {
      'Content-Type': 'application/x-yaml; charset=utf-8',
      'Last-Modified': lastModifiedTime,
      'Cache-Control': 'no-cache'
    });
    if (requestPath === '/bundled.yaml') {
      res.end(bundledYaml);
    } else {
      // Serve openapi.yaml content
      const openapiContent = fs.existsSync(OPENAPI_FILE) ? fs.readFileSync(OPENAPI_FILE, 'utf8') : '';
      res.end(openapiContent);
    }
  } else {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Not Found');
  }
});

server.listen(PORT, () => {
  console.log(`\n🚀 Redoc preview server running on http://localhost:${PORT}`);
  console.log('📚 Using open-source Redoc library');
  console.log('🔄 Hot reload enabled - watching for file changes...');
  console.log('👁️  Open your browser to view the API documentation\n');
});

// Handle graceful shutdown
process.on('SIGINT', () => {
  console.log('\n\nShutting down preview server...');
  server.close(() => {
    console.log('Preview server closed.');
    process.exit(0);
  });
});

